[theme]
base = "dark"
primaryColor = "#58EFC9"
backgroundColor = "#020706"
secondaryBackgroundColor = "#061D17"
textColor = "#E8FFF8"
font = "monospace"

[server]
headless = true
maxUploadSize = 5

[browser]
gatherUsageStats = false
